name: Deploy to EC2

# on:
#   push:
#     branches:
#       - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y nodejs
          sudo apt-get install -y npm
          npm install

      - name: Build and test
        run: npm run build && npm run test

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /express-app 
            git pull
            npm install --ignore mongodb-memory-server nodemon supertest
            npm run build
            npm run afterBuild
            pm2 restart express-app
